import { Container } from "inversify";
import { TYPES } from "./types";
import IDatabaseConnection from "@infra/data/connection/IDatabaseConnection";
import PgPromiseAdapter from "@infra/data/connection/PgPromiseAdapter";
import { CriteriaBuilder } from "@infra/data/CriteriaBuilder";
import IPositionRepository from "@domain/repositories/IPositionRepository";
import PositionRepository from "@infra/data/repositories/PositionRepository";
import IPositionQuery from "@application/contracts/queries/IPositionQuery";
import PositionQuery from "@infra/data/queries/PositionQuery";
import ICreatePosition from "@application/modules/positions/createPosition/ICreatePosition";
import CreatePosition from "@application/modules/positions/createPosition/CreatePosition";
import CreatePositionEndpoint from "@application/modules/positions/createPosition/CreatePositionEndpoint";
import IUpdatePosition from "@application/modules/positions/updatePosition/IUpdatePosition";
import UpdatePosition from "@application/modules/positions/updatePosition/UpdatePosition";
import UpdatePositionEndpoint from "@application/modules/positions/updatePosition/UpdatePositionEndpoint";
import IDeletePosition from "@application/modules/positions/deletePosition/IDeletePosition";
import DeletePosition from "@application/modules/positions/deletePosition/DeletePosition";
import DeletePositionEndpoint from "@application/modules/positions/deletePosition/DeletePositionEndpoint";
import IGetPosition from "@application/modules/positions/getPosition/IGetPosition";
import GetPosition from "@application/modules/positions/getPosition/GetPosition";
import GetPositionEndpoint from "@application/modules/positions/getPosition/GetPositionEndpoint";
import ISearchPositions from "@application/modules/positions/searchPositions/ISearchPositions";
import SearchPositions from "@application/modules/positions/searchPositions/SearchPositions";
import SearchPositionsEndpoint from "@application/modules/positions/searchPositions/SearchPositionsEndpoint";

const container = new Container();

container.bind<IDatabaseConnection>(TYPES.IDatabaseConnection).to(PgPromiseAdapter).inSingletonScope();
container.bind(CriteriaBuilder).toSelf().inRequestScope;
container.bind<IPositionRepository>(TYPES.IPositionRepository).to(PositionRepository).inRequestScope();
container.bind<IPositionQuery>(TYPES.IPositionQuery).to(PositionQuery).inRequestScope();
container.bind<ICreatePosition>(TYPES.ICreatePosition).to(CreatePosition).inRequestScope();
container.bind(CreatePositionEndpoint).toSelf().inRequestScope;
container.bind<IUpdatePosition>(TYPES.IUpdatePosition).to(UpdatePosition).inRequestScope();
container.bind(UpdatePositionEndpoint).toSelf().inRequestScope;
container.bind<IDeletePosition>(TYPES.IDeletePosition).to(DeletePosition).inRequestScope();
container.bind(DeletePositionEndpoint).toSelf().inRequestScope;
container.bind<IGetPosition>(TYPES.IGetPosition).to(GetPosition).inRequestScope();
container.bind(GetPositionEndpoint).toSelf().inRequestScope;
container.bind<ISearchPositions>(TYPES.ISearchPositions).to(SearchPositions).inRequestScope();
container.bind(SearchPositionsEndpoint).toSelf().inRequestScope;

export { container };
